
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace sozluk123.Models
{

using System;
    using System.Collections.Generic;
    
public partial class baslik
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public baslik()
    {

        this.active = true;

    }


    public System.Guid ID { get; set; }

    public string baslik_ismi { get; set; }

    public Nullable<System.Guid> yazar_id { get; set; }

    public Nullable<System.DateTime> kayit_tarih { get; set; }

    public Nullable<bool> active { get; set; }

    public string baslik_icerik { get; set; }



    public virtual yazar yazar { get; set; }

}

}
