
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace sozluk123.Models
{

using System;
    using System.Collections.Generic;
    
public partial class entry
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public entry()
    {

        this.active = true;

        this.is_comment = false;

        this.entry_yazar = new HashSet<entry_yazar>();

    }


    public System.Guid ID { get; set; }

    public string entry_ismi { get; set; }

    public string entry_icerik { get; set; }

    public Nullable<System.Guid> yazar_id { get; set; }

    public Nullable<System.DateTime> kayit_tarih { get; set; }

    public Nullable<bool> active { get; set; }

    public Nullable<int> post_like { get; set; }

    public Nullable<bool> is_comment { get; set; }



    public virtual yazar yazar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<entry_yazar> entry_yazar { get; set; }

}

}
