
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace sozluk123.Models
{

using System;
    using System.Collections.Generic;
    
public partial class entry_yazar
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public entry_yazar()
    {

        this.is_active = true;

    }


    public System.Guid ID { get; set; }

    public Nullable<System.Guid> entry_ID { get; set; }

    public Nullable<System.Guid> yazar_ID { get; set; }

    public string comment { get; set; }

    public Nullable<bool> is_active { get; set; }

    public Nullable<System.DateTime> kayit_tarih { get; set; }



    public virtual entry entry { get; set; }

    public virtual yazar yazar { get; set; }

}

}
