

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace sozluk123.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class sozluk1Entities1 : DbContext
{
    public sozluk1Entities1()
        : base("name=sozluk1Entities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<baslik> baslik { get; set; }

    public virtual DbSet<entry> entry { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<yazar> yazar { get; set; }

    public virtual DbSet<systranschemas> systranschemas { get; set; }

    public virtual DbSet<entry_yazar> entry_yazar { get; set; }

    public virtual DbSet<Users> Users { get; set; }

}

}

